# Generated by Django 3.2 on 2021-05-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210522_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsidy',
            options={'verbose_name': 'Subsidy', 'verbose_name_plural': 'Subsidies'},
        ),
    ]
