# Generated by Django 3.2 on 2021-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_subsidy_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.JSONField(blank=True, null=True, verbose_name='Company'),
        ),
    ]
