# Generated by Django 3.2 on 2021-05-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210522_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='inn',
            new_name='company',
        ),
    ]
