# Generated by Django 3.2 on 2021-05-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_inn_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidy',
            name='description',
        ),
        migrations.AddField(
            model_name='subsidy',
            name='info',
            field=models.JSONField(blank=True, null=True, verbose_name='info'),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='kbk',
            field=models.CharField(default='none', max_length=250, verbose_name='KBK'),
        ),
    ]
