# Generated by Django 3.2 on 2021-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210522_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidy',
            name='name',
        ),
        migrations.AddField(
            model_name='subsidy',
            name='purpose',
            field=models.CharField(default='none', max_length=250, verbose_name='Purpose'),
        ),
    ]
